/**
 * @fileoverview PoweredBy 组件 - 显示应用提供者和 AI 生成内容免责声明
 * @author 祁筱欣
 * @date 2026-02-11
 * @since 2026-02-11
 * @contact qixiaoxin@stu.sqxy.edu.cn
 * @LICENSE AGPL-3.0 license
 * @remark
 * 该组件显示应用的提供者信息和 AI 生成内容的免责声明。
 * 根据环境变量 VITE_APP_REGION 决定跳转到中国官网还是全球官网。
 * 支持的功能：
 * - 显示 "Powered By" 标识
 * - 根据语言显示对应的免责声明文本
 * - 支持中文、英文、日文三种语言
 * 使用方式：
 * ```tsx
 * <PoweredBy language="chinese" />
 * ```
 */

/**
 * PoweredBy 组件
 * 显示应用提供者和 AI 生成内容免责声明
 *
 * @param language - 语言类型：'chinese' | 'english' | 'japanese'
 * @returns 返回包含 PoweredBy 标识和免责声明的 JSX 元素
 */
export default function PoweredBy({ language }: { language: 'chinese' | 'english' | 'japanese' }) {
  const href = import.meta.env.VITE_APP_REGION ?
    import.meta.env.VITE_APP_OFFICIAL_WEBSITE_URL_GLOBAL :
    import.meta.env.VITE_APP_OFFICIAL_WEBSITE_URL_CHINA
  return (
    <>
      <div
        className="flex justify-center items-center gap-1 mb-2"
        style={{ color: "rgb(102, 102, 102)", fontSize: "12px" }}
      >
        Powered By
        <a target="_blank" href={href}>
          <img
            className="object-contain"
            src="https://file.302.ai/gpt/imgs/91f7b86c2cf921f61e8cf9dc7b1ec5ee.png"
            alt="gpt302"
            width="55"
          />
        </a>
      </div>
      <div className="text-center mb-1" style={{ color: "rgb(200, 200, 200)", fontSize: "12px" }}>
        {language === 'chinese' ? "内容由AI生成，仅供参考" : language === 'japanese' ? 'コンテンツは参照用にAIによって生成される' : "Content generated by AI, for reference only"}
      </div>
    </>
  );
}
